### ISSUE TITLE
Please do the right thing

### ISSUE THREAD

**Issue by p40sp40r0us** [JeffNeff/blog#5]
You don't know me, and you'll probably delete this... but I know there are two sides to each story.

I am writing to ask you to do the right thing.  I bought heavily into grams... all the way down (along with many others).. losing time and money, and it's hurting pretty bad financially (most of the buys on xeggex were me).   I recognize that as the dev you did almost all the work to bring it to this point and I'm sure you're feeling bitter as well, but now it's worth almost nothing... so why does it even matter?  I'm sure the reason the price dropped had to do with many factors (Txbit etc), so this is not a blame game for me, just trying to help myself and others resurrect this project.  Even if you want to buy back in you can do so now at discounted prices lol.

You can help many people and walk away at the same time...  so can you please just hand off your dev wallet keys to ProjectCarey (or really whoever on the team)?  

I know there are risks, but I have a family and lost a lot of money ... and doing this enables that even if platform doesn't launch, at least the block chain won't die and something can be salvaged.  Thank you

**Comment by JeffNeff** [comment]
im  happy to do this. I explained why I had to leave ( health and legal reasons)  and offered all the keys. instead of taking it and keeping on they chose to talk shit.

**Comment by p40sp40r0us** [comment]
I totally understand, there was some nasty things said from people who didn't put the actual "real" work in which make crypto tick.. , and I was pretty positive that most of it was untrue... for instance I noticed that the wallet amounts hadn't changed since 4 months ago... you wouldn't do that kind of work without believing in the project...I knew there was something personal going on, because I've been through bad projects and this isn't one of them.. But it's more than the rest of the team.  If you want you can give me the keys, and I'll create a multi-sig wallet to make it more fair.  But there are a lot of "normal" non shit talking people hurting, and I think the project is cool and can still live on... you can send it to my github email or to Carey (who really didn't say anything too bad publicly if it helps)

**Comment by p40sp40r0us** [comment]
thank you

**Comment by JeffNeff** [comment]
Ill do one better for you... they deleted the code and are denying help to continue pushing it... how about instead we give it to everyone?

**Comment by JeffNeff** [comment]
> thank you


@p40sp40r0us 
https://github.com/JeffNeff/TeaParty

Not much for documentation.. but i can work on that.

**Comment by JeffNeff** [comment]
@p40sp40r0us 

here is the frontend too -> https://github.com/JeffNeff/tea

**Comment by JeffNeff** [comment]
PartyBridge stuff as well :) 

https://github.com/JeffNeff/PartyShim
https://github.com/JeffNeff/PartyBridge
https://github.com/JeffNeff/partybridge-ui
